version: "3"
services:
  knowledge-repo:
    build: .
    #env_file:
      #- ./.env.docker
    ports:
      - "7000:7000"
    volumes:
      - ./repo:/app/repo
    command: ["knowledge_repo", "--repo", "/app/repo", "runserver"]
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: alwas
    environment: 
      MYSQL_ROOT_PASSWORD: example-pass
  adminer:
    image: adminer
    restart: always
    ports: 
      - 8080:8080